services:
  nginx:
    networks:
      default:
        priority: 1
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.5
    mac_address: 00:16:3e:ca:7e:30
  gmod:
    environment:
      SRCDS_IP: 10.3.10.4
    networks:
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.4
    mac_address: 00:16:3e:ca:7e:31

networks:
  vlan3:
    external: true
  default:
    enable_ipv6: true
    ipam:
      config:
        - subnet: fdd8:2357:cb1a:86c2::/64
          gateway: fdd8:2357:cb1a:86c2::1
