services:
  nginx:
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      default:
        priority: 1
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.5
  gmod:
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      SRCDS_IP: 10.3.10.4
    networks:
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.4

networks:
  vlan3:
    external: true
