version: "2.4"
services:
  mysql:
    image: percona:latest
    restart: always
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - spaceage_mysql:/var/lib/mysql
  php:
    #image: php:fpm-alpine
    build: php
    restart: always
    user: 1000:1000
    links:
      - mysql:mysql
    volumes:
      - spaceage_wwwroot:/var/www
  tts:
    # TODO
    image: ghcr.io/spaceagemp/tts/tts:latest
    init: yes
    restart: always
    volumes:
      - spaceage_tts_awscreds:/home/tts/.aws
  nginx:
    #image: nginx:alpine
    build: nginx
    restart: always
    volumes:
      - spaceage_wwwroot:/var/www
      - spaceage_ssl:/etc/nginx/ssl
    links:
      - php:php
      - tts:tts
    ports:
      - 443:443

volumes:
  spaceage_wwwroot:
    external: true
  spaceage_mysql:
    external: true
  spaceage_ssl:
    external: true
  spaceage_tts_awscreds:
    external: true
