services:
  mysql:
    dns:
    - 10.6.0.53
  tts:
    dns:
    - 10.6.0.53
  api:
    dns:
    - 10.6.0.53
  nginx:
    mac_address: 62:bf:fb:e4:89:5d
    dns:
    - 10.3.0.53
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      default:
        priority: 1
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.5
  gmod:
    mac_address: 5e:47:05:fc:f8:90
    dns:
    - 10.3.0.53
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      SRCDS_IP: 10.3.10.4
    networks:
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.4

networks:
  vlan3:
    external: true
