services:
  mysql:
    dns:
    - 10.6.0.53
  tts:
    dns:
    - 10.6.0.53
  api:
    dns:
    - 10.6.0.53
  nginx:
    dns:
    - 10.3.0.53
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    networks:
      default:
        priority: 1
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.5
        mac_address: 62:bf:fb:e4:89:5d
  gmod:
    dns:
    - 10.3.0.53
    extra_hosts:
      - spaceage.mp:10.3.10.9
      - www.spaceage.mp:10.3.10.9
      - api.spaceage.mp:10.3.10.5
      - tts.spaceage.mp:10.3.10.5
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
    environment:
      SRCDS_IP: 10.3.10.4
    networks:
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.4
        mac_address: 5e:47:05:fc:f8:90
  website:
    dns:
    - 10.3.0.53
    networks:
      vlan3:
        priority: 100
        ipv4_address: 10.3.10.9
        mac_address: 5e:1a:40:6a:64:06

networks:
  vlan3:
    external: true
