#!/bin/sh
set -e

adduser -D -s /bin/false -u "$PUID" -g "$PGID" appuser || true

cat > /tmp/crontab <<EOF
* * * * * sleep 54; /usr/local/bin/php /var/www/forums/cmd.php xf:run-jobs
*/5 * * * * sleep 24; /usr/local/bin/php /var/www/forums/sa_group_sync.php
EOF
crontab -u appuser /tmp/crontab
rm -f /tmp/crontab

exec crond -f
